name: RISC-V ISA Build

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a new RISC-V ISA release if set to true'
        required: false
        default: 'false'
      target_branch:
        description: 'Target Branch'
        required: true
        default: 'main'
      release_notes:
        description: 'Release Notes'
        required: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: 
      - riscv-builders
      - soc-spacemit-k1

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
      
    # Set the short SHA for use in artifact names
    - name: Set short SHA
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV
      
    # Get the current date
    - name: Get current date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Resovle dependency
      run: ./dependency.sh

    - name: Build document
      run: make build-no-container -j$(nproc)

    - name: echo
      run: ls -lsh ${{ github.workspace }}/build/*
